services:
  - type: web
    name: ask-al-viejo-loco
    env: python
    region: oregon
    plan: starter
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: streamlit run ask_the_archive.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true --server.enableCORS=false --server.enableXsrfProtection=false
    envVars:
      - key: OPENAI_API_KEY
        sync: false
